import "./globals.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className="w-[100%] h-[100%] m-0 flex justify-center align-middle">
          {/* left */}
          <div className="hidden lg:block lg:min-h-screen lg:w-[calc(80%-450px)] "></div>

          {/* center */}
          <div className="max-w-[450px] shadow min-h-screen flex-1 lg:m-auto">
            {children}
          </div>

          {/* right */}
          <div className="hidden lg:block min-h-screen w-1/5"></div>
        </div>
      </body>
    </html>
  );
}
